/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as LinksRouteImport } from './routes/links'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ApiPublicTraceRouteImport } from './routes/api/public/trace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTraceRoute = ApiPublicTraceRouteImport.update({
  id: '/api/public/trace',
  path: '/api/public/trace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/links': typeof LinksRoute
  '/r/$id': typeof RIdRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/trace': typeof ApiPublicTraceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/links': typeof LinksRoute
  '/r/$id': typeof RIdRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/trace': typeof ApiPublicTraceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/links': typeof LinksRoute
  '/r/$id': typeof RIdRoute
  '/s/$slug': typeof SSlugRoute
  '/api/public/trace': typeof ApiPublicTraceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api-docs' | '/links' | '/r/$id' | '/s/$slug' | '/api/public/trace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api-docs' | '/links' | '/r/$id' | '/s/$slug' | '/api/public/trace'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/links'
    | '/r/$id'
    | '/s/$slug'
    | '/api/public/trace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  LinksRoute: typeof LinksRoute
  RIdRoute: typeof RIdRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicTraceRoute: typeof ApiPublicTraceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trace': {
      id: '/api/public/trace'
      path: '/api/public/trace'
      fullPath: '/api/public/trace'
      preLoaderRoute: typeof ApiPublicTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  LinksRoute: LinksRoute,
  RIdRoute: RIdRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicTraceRoute: ApiPublicTraceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
